language: cpp

compiler:
  - clang
  - gcc

# use travis-ci docker based infrastructure
sudo: false

addons:
  apt:
    sources:
    - kubuntu-backports
    - ubuntu-toolchain-r-test
    packages:
    - libeigen3-dev
    - libclang-3.4-dev
    - llvm-3.4-dev
    - clang-3.4
    - gcc-4.8
    - g++-4.8
    - cmake
    - libgtest-dev
    - gdb
    - texlive-extra-utils
#    - cppad

env:
  global:
    #- CPPAD_HOME=`pwd`/cppadcg_deps/cppad/install/include
    - CPPAD_HOME=`pwd`/cppadcg_deps/CppAD-20160000.1/install/include

before_install:
  - if [ "$CXX" == "g++" ]; then export CC="$(which gcc-4.8)" CXX="$(which g++-4.8)"; fi
#  - if [ "$CXX" == "clang++" ]; then export CC="$(which clang-3.4)" CXX="$(which clang++-3.4)"; fi
    
install:
  - mkdir cppadcg_deps
  - cd cppadcg_deps
#  - git clone https://github.com/coin-or/CppAD.git cppad
#  - cd cppad
  - wget http://github.com/coin-or/CppAD/archive/20160000.1.tar.gz
  - tar -xzf 20160000.1.tar.gz
  - cd CppAD-20160000.1
  - mkdir build
  - mkdir install
  - cd build
  - cmake -Dcppad_prefix:PATH=../install -Dcppad_cxx_flags="-Wall -std=c++11 -Wshadow" ..
  - make install
  - cd ../../..
    
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DUSE_VALGRIND=OFF -DGOOGLETEST_SVN=OFF -DENABLE_THREAD_POOL_TESTS=OFF ..
  - cd test
  - make
  - make test

os:
  - linux
